// ============================================================
//  Mock data — Onboarding LMS prototype
//  One hire: Maya Putri, Backend Engineer, joined 2026-03-09
//  6-month track. Phase 3 (Weeks 2-4) currently active.
// ============================================================

export const LMS_DATA = (() => {
  // i18n
  const T = {
    en: {
      lang: 'EN',
      nav_home: 'Home',
      nav_journey: 'My Journey',
      nav_report: 'My Report',
      nav_assistant: 'Assistant',
      nav_help: 'Help & Buddy',
      nav_settings: 'Settings',
      nav_assessments: 'Assessments',
      progress_title: 'Track progress',
      progress_sub: 'modules complete',
      progress_h: 'You\'re on track. Phase 3 wraps Apr 6.',
      crumb_home: 'Today',
      crumb_journey: 'Journey',
      crumb_module: 'Module',
      crumb_viewer: 'Viewer',
      crumb_quiz: 'Assessment',
      crumb_feedback: 'Feedback',
      crumb_report: 'My Report',
      crumb_assistant: 'Assistant',
      crumb_help: 'Help & Buddy',
      crumb_settings: 'Settings',
      crumb_assessments: 'Assessments',
      crumb_assessment: 'Assessment',
      greet_morning: 'Good morning,',
      greet_afternoon: 'Good afternoon,',
      next_up: 'Next up',
      day: 'Day',
      of_track: 'of your onboarding',
      due_in: 'Due in',
      duration: 'Duration',
      category: 'Category',
      phase: 'Phase',
      start_now: 'Start module',
      resume: 'Resume where I left off',
      mark_complete: 'Mark complete',
      this_week: 'This week',
      recent: 'Recently completed',
      buddy: 'Your buddy',
      message_buddy: 'Send a message',
      stat_days: 'Days into onboarding',
      stat_done: 'Modules complete',
      stat_streak: 'Day streak',
      stat_phase_pct: 'Current phase',
      jr_title: 'Your onboarding',
      jr_em: 'journey',
      jr_sub: 'Six months of structured learning, grouped into phases. Pace yourself — completing on time matters more than going fast.',
      tl_today: 'You are here · day 22',
      due: 'Due',
      modules: 'modules',
      hours: 'hr',
      complete: 'Complete',
      in_progress: 'In progress',
      locked: 'Locked',
      not_started: 'Not started',
      overdue: 'Overdue',
      back_journey: 'Back to my journey',
      pretest_title: 'Pre-test',
      pretest_sub: 'Optional · 5 questions · measures starting knowledge',
      content_title: 'Module content',
      content_sub: 'Read, watch, then proceed',
      posttest_title: 'Post-test',
      posttest_sub: 'Required · 10 questions · pass at 70%',
      feedback_title: 'Module feedback',
      feedback_sub: 'Optional · helps HR improve onboarding',
      start_pretest: 'Take pre-test',
      start_content: 'Start content',
      start_posttest: 'Take post-test',
      skip_for_now: 'Skip for now',
      give_feedback: 'Give feedback',
      content_open: 'Open',
      content_play: 'Play',
      content_view: 'View',
      done: 'Done',
      via_sharepoint: 'via SharePoint',
      viewer_transcript: 'Transcript',
      viewer_speed: 'Speed',
      viewer_next: 'Mark as watched & continue',
      viewer_continue: 'Continue to post-test',
      module_contents: 'In this module',
      quiz_q: 'Question',
      quiz_of: 'of',
      quiz_threshold: 'Pass at 70%',
      quiz_attempt: 'Attempt 1 of unlimited',
      quiz_prev: 'Back',
      quiz_next: 'Next',
      quiz_submit: 'Submit answers',
      quiz_pass: 'You passed',
      quiz_fail: 'Not quite — try again',
      quiz_score: 'Your score',
      quiz_correct: 'Correct',
      quiz_time: 'Time taken',
      quiz_pass_msg: 'This module is now complete. Your buddy and hiring manager have been notified.',
      quiz_fail_msg: 'You need 70% to complete this module. Review the material and retake when ready (24-hour cooldown).',
      quiz_review: 'Review answers',
      quiz_continue: 'Continue to feedback',
      quiz_retake: 'Retake (available in 24h)',
      quiz_back: 'Back to module',
      fb_eyebrow: 'Module feedback',
      fb_title: 'How was this module?',
      fb_sub: 'Two minutes. Anonymous to your manager — HR sees the aggregate.',
      fb_q1: 'Material was useful for my role',
      fb_q1_h: 'Did it help you do real work?',
      fb_q2: 'Length felt right',
      fb_q2_h: 'Too long, too short, or about right?',
      fb_q3: 'Variety of activities',
      fb_q3_h: 'Mix of video, reading, exercises.',
      fb_q4: 'Anything else? (optional)',
      fb_q4_h: 'What worked, what didn\'t.',
      fb_placeholder: 'Optional comment — what would you change?',
      fb_submit: 'Submit feedback',
      fb_skip: 'Skip',
      report_l: 'Personal report',
      report_title: 'You\'re ',
      report_em: 'on track.',
      report_sub: 'Started March 9. You\'ve completed 9 of 28 modules and earned 2 phase certificates. Keep this pace and you\'ll finish onboarding two days early.',
      report_certs: 'Certificates',
      report_certs_done: 'earned',
      report_scores: 'Quiz scores',
      view_cert: 'View',
      download: 'Download',
      cert_phase: 'Phase certificate',
      cert_final: 'Final onboarding certificate',
      cert_modal_l: 'Certificate of completion',
      cert_modal_for: 'for completing',
      cert_modal_signed: 'Issued',
      cert_modal_id: 'Certificate ID',
      cert_modal_authority: 'HR — PT Myralix Indonesia',
      hi_today: 'Here\'s what matters today.',
    },
    id: {
      lang: 'ID',
      nav_home: 'Beranda',
      nav_journey: 'Perjalanan Saya',
      nav_report: 'Laporan Saya',
      nav_assistant: 'Asisten',
      nav_help: 'Bantuan & Buddy',
      nav_settings: 'Pengaturan',
      nav_assessments: 'Asesmen',
      progress_title: 'Progres jalur',
      progress_sub: 'modul selesai',
      progress_h: 'Anda sesuai jadwal. Fase 3 berakhir 6 April.',
      crumb_home: 'Hari Ini',
      crumb_journey: 'Perjalanan',
      crumb_module: 'Modul',
      crumb_viewer: 'Pemutar',
      crumb_quiz: 'Asesmen',
      crumb_feedback: 'Umpan Balik',
      crumb_report: 'Laporan Saya',
      crumb_assistant: 'Asisten',
      crumb_help: 'Bantuan & Buddy',
      crumb_settings: 'Pengaturan',
      crumb_assessments: 'Asesmen',
      crumb_assessment: 'Asesmen',
      greet_morning: 'Selamat pagi,',
      greet_afternoon: 'Selamat siang,',
      next_up: 'Berikutnya',
      day: 'Hari',
      of_track: 'dari onboarding Anda',
      due_in: 'Tenggat',
      duration: 'Durasi',
      category: 'Kategori',
      phase: 'Fase',
      start_now: 'Mulai modul',
      resume: 'Lanjutkan dari terakhir',
      mark_complete: 'Tandai selesai',
      this_week: 'Minggu ini',
      recent: 'Baru selesai',
      buddy: 'Buddy Anda',
      message_buddy: 'Kirim pesan',
      stat_days: 'Hari onboarding',
      stat_done: 'Modul selesai',
      stat_streak: 'Hari berurut',
      stat_phase_pct: 'Fase saat ini',
      jr_title: 'Perjalanan',
      jr_em: 'onboarding Anda',
      jr_sub: 'Enam bulan pembelajaran terstruktur, dikelompokkan per fase. Atur ritme — selesai tepat waktu lebih penting daripada cepat.',
      tl_today: 'Anda di sini · hari 22',
      due: 'Tenggat',
      modules: 'modul',
      hours: 'jam',
      complete: 'Selesai',
      in_progress: 'Berjalan',
      locked: 'Terkunci',
      not_started: 'Belum mulai',
      overdue: 'Lewat tenggat',
      back_journey: 'Kembali ke perjalanan',
      pretest_title: 'Pre-test',
      pretest_sub: 'Opsional · 5 soal · mengukur pengetahuan awal',
      content_title: 'Materi modul',
      content_sub: 'Baca, tonton, lalu lanjutkan',
      posttest_title: 'Post-test',
      posttest_sub: 'Wajib · 10 soal · lulus di 70%',
      feedback_title: 'Umpan balik modul',
      feedback_sub: 'Opsional · membantu HR memperbaiki onboarding',
      start_pretest: 'Kerjakan pre-test',
      start_content: 'Mulai materi',
      start_posttest: 'Kerjakan post-test',
      skip_for_now: 'Lewati dulu',
      give_feedback: 'Beri umpan balik',
      content_open: 'Buka',
      content_play: 'Putar',
      content_view: 'Lihat',
      done: 'Selesai',
      via_sharepoint: 'via SharePoint',
      viewer_transcript: 'Transkrip',
      viewer_speed: 'Kecepatan',
      viewer_next: 'Tandai ditonton & lanjut',
      viewer_continue: 'Lanjut ke post-test',
      module_contents: 'Isi modul',
      quiz_q: 'Soal',
      quiz_of: 'dari',
      quiz_threshold: 'Lulus di 70%',
      quiz_attempt: 'Percobaan 1 tanpa batas',
      quiz_prev: 'Kembali',
      quiz_next: 'Lanjut',
      quiz_submit: 'Kirim jawaban',
      quiz_pass: 'Anda lulus',
      quiz_fail: 'Belum berhasil — coba lagi',
      quiz_score: 'Skor Anda',
      quiz_correct: 'Benar',
      quiz_time: 'Waktu',
      quiz_pass_msg: 'Modul ini selesai. Buddy dan atasan langsung Anda telah diberi tahu.',
      quiz_fail_msg: 'Anda butuh 70% untuk menyelesaikan modul. Tinjau ulang materi dan ulangi (cooldown 24 jam).',
      quiz_review: 'Tinjau jawaban',
      quiz_continue: 'Lanjut ke umpan balik',
      quiz_retake: 'Ulangi (tersedia 24 jam)',
      quiz_back: 'Kembali ke modul',
      fb_eyebrow: 'Umpan balik modul',
      fb_title: 'Bagaimana modul ini?',
      fb_sub: 'Dua menit. Anonim ke atasan — HR melihat agregat.',
      fb_q1: 'Materi bermanfaat untuk peran saya',
      fb_q1_h: 'Apakah membantu pekerjaan nyata?',
      fb_q2: 'Durasi terasa pas',
      fb_q2_h: 'Terlalu panjang, pendek, atau pas?',
      fb_q3: 'Variasi aktivitas',
      fb_q3_h: 'Campuran video, bacaan, latihan.',
      fb_q4: 'Hal lain? (opsional)',
      fb_q4_h: 'Apa yang baik, apa yang kurang.',
      fb_placeholder: 'Komentar opsional — apa yang akan Anda ubah?',
      fb_submit: 'Kirim umpan balik',
      fb_skip: 'Lewati',
      report_l: 'Laporan pribadi',
      report_title: 'Anda ',
      report_em: 'sesuai jadwal.',
      report_sub: 'Mulai 9 Maret. Anda telah menyelesaikan 9 dari 28 modul dan memperoleh 2 sertifikat fase. Dengan ritme ini Anda akan selesai dua hari lebih cepat.',
      report_certs: 'Sertifikat',
      report_certs_done: 'diperoleh',
      report_scores: 'Skor kuis',
      view_cert: 'Lihat',
      download: 'Unduh',
      cert_phase: 'Sertifikat fase',
      cert_final: 'Sertifikat onboarding akhir',
      cert_modal_l: 'Sertifikat penyelesaian',
      cert_modal_for: 'atas penyelesaian',
      cert_modal_signed: 'Diterbitkan',
      cert_modal_id: 'ID Sertifikat',
      cert_modal_authority: 'HR — PT Myralix Indonesia',
      hi_today: 'Inilah yang penting hari ini.',
    }
  };

  const PHASES = [
    { id: 1, key: 'Pre-board',     when: 'Before Day 1',    range: 'Mar 2 – Mar 8',   status: 'done' },
    { id: 2, key: 'Day 1 – Wk 1',  when: 'Orientation',     range: 'Mar 9 – Mar 15',  status: 'done' },
    { id: 3, key: 'Weeks 2 – 4',   when: 'Foundation',      range: 'Mar 16 – Apr 5',  status: 'active' },
    { id: 4, key: 'Months 2 – 3',  when: 'Role depth',      range: 'Apr 6 – Jun 8',   status: 'locked' },
    { id: 5, key: 'Months 4 – 6',  when: 'Integration',     range: 'Jun 9 – Sep 6',   status: 'locked' },
    { id: 6, key: 'Months 7 – 12', when: 'Mastery',         range: 'Sep 7 – Mar 8',   status: 'locked' },
  ];

  // Each module has: id, title (en/id), category, phase, type, duration, status, due, score, threshold
  const MODULES = [
    // Phase 1 - Pre-board (DONE)
    { id: 'm01', t_en: 'Welcome to Myralix',                  t_id: 'Selamat datang di Myralix',         cat: 'Welcome',       phase: 1, dur: 25, status: 'done', score: 90, due: 'Mar 8' },
    { id: 'm02', t_en: 'Pre-arrival checklist & IT setup',     t_id: 'Daftar persiapan & setup IT',         cat: 'Tools',         phase: 1, dur: 20, status: 'done', score: 100, due: 'Mar 8' },
    { id: 'm03', t_en: 'Meet your buddy',                       t_id: 'Kenalan dengan buddy Anda',           cat: 'People',        phase: 1, dur: 15, status: 'done', score: null, due: 'Mar 8' },

    // Phase 2 - Day 1 to Week 1 (DONE)
    { id: 'm04', t_en: 'Company history & mission',             t_id: 'Sejarah & misi perusahaan',           cat: 'Welcome',       phase: 2, dur: 40, status: 'done', score: 95, due: 'Mar 11' },
    { id: 'm05', t_en: 'Our values, in practice',               t_id: 'Nilai kami, dalam praktik',           cat: 'Welcome',       phase: 2, dur: 35, status: 'done', score: 80, due: 'Mar 12' },
    { id: 'm06', t_en: 'K3 — Workplace safety',                 t_id: 'K3 — Keselamatan kerja',              cat: 'Compliance',    phase: 2, dur: 60, status: 'done', score: 85, due: 'Mar 14' },
    { id: 'm07', t_en: 'Data privacy & confidentiality',        t_id: 'Privasi data & kerahasiaan',          cat: 'Compliance',    phase: 2, dur: 45, status: 'done', score: 90, due: 'Mar 14' },
    { id: 'm08', t_en: 'Communication norms — Slack, email',    t_id: 'Norma komunikasi — Slack, email',     cat: 'Tools',         phase: 2, dur: 30, status: 'done', score: 100, due: 'Mar 15' },
    { id: 'm09', t_en: 'Code of conduct',                       t_id: 'Kode etik',                            cat: 'Compliance',    phase: 2, dur: 35, status: 'done', score: 75, due: 'Mar 15' },

    // Phase 3 - Weeks 2-4 (ACTIVE) - one in progress, rest queued
    { id: 'm10', t_en: 'Anti-harassment & inclusion',           t_id: 'Anti-pelecehan & inklusi',            cat: 'Compliance',    phase: 3, dur: 50, status: 'active', score: null, due: 'Mar 25', nextStep: 'posttest' },
    { id: 'm11', t_en: 'Anti-corruption — what to refuse',      t_id: 'Anti-korupsi — apa yang ditolak',     cat: 'Compliance',    phase: 3, dur: 40, status: 'todo', score: null, due: 'Mar 28' },
    { id: 'm12', t_en: 'Engineering practices at Myralix',     t_id: 'Praktik engineering di Myralix',     cat: 'Role',          phase: 3, dur: 90, status: 'todo', score: null, due: 'Mar 30' },
    { id: 'm13', t_en: 'Code review culture',                   t_id: 'Budaya code review',                  cat: 'Role',          phase: 3, dur: 60, status: 'todo', score: null, due: 'Apr 2' },
    { id: 'm14', t_en: 'Sprint rituals & ceremonies',           t_id: 'Ritual & seremoni sprint',            cat: 'People',        phase: 3, dur: 45, status: 'todo', score: null, due: 'Apr 4' },
    { id: 'm15', t_en: 'Production access & incident response', t_id: 'Akses produksi & respons insiden',    cat: 'Tools',         phase: 3, dur: 70, status: 'todo', score: null, due: 'Apr 5' },

    // Phase 4 - Months 2-3 (LOCKED)
    { id: 'm16', t_en: 'Service ownership model',               t_id: 'Model kepemilikan layanan',           cat: 'Role',          phase: 4, dur: 60, status: 'locked', score: null, due: 'Apr 18' },
    { id: 'm17', t_en: 'Architecture deep-dive',                t_id: 'Arsitektur — penyelaman dalam',        cat: 'Role',          phase: 4, dur: 120, status: 'locked', score: null, due: 'May 2' },
    { id: 'm18', t_en: 'Working with product & design',         t_id: 'Bekerja dengan produk & desain',      cat: 'People',        phase: 4, dur: 45, status: 'locked', score: null, due: 'May 16' },
    { id: 'm19', t_en: 'Customer empathy — sit with support',   t_id: 'Empati pelanggan — duduk dengan support', cat: 'People',    phase: 4, dur: 90, status: 'locked', score: null, due: 'May 30' },
    { id: 'm20', t_en: 'On-call expectations',                  t_id: 'Ekspektasi on-call',                  cat: 'Role',          phase: 4, dur: 55, status: 'locked', score: null, due: 'Jun 8' },

    // Phase 5 - Months 4-6 (LOCKED)
    { id: 'm21', t_en: 'Feedback culture — giving & receiving', t_id: 'Budaya feedback — memberi & menerima', cat: 'Growth',       phase: 5, dur: 50, status: 'locked', score: null, due: 'Jun 28' },
    { id: 'm22', t_en: 'Performance review mechanics',          t_id: 'Mekanika review performa',            cat: 'Growth',        phase: 5, dur: 40, status: 'locked', score: null, due: 'Jul 20' },
    { id: 'm23', t_en: 'Probation milestone — 90 day review',   t_id: 'Tonggak probasi — review 90 hari',    cat: 'Growth',        phase: 5, dur: 30, status: 'locked', score: null, due: 'Aug 14' },
    { id: 'm24', t_en: 'Cross-functional collaboration',        t_id: 'Kolaborasi lintas fungsi',            cat: 'People',        phase: 5, dur: 60, status: 'locked', score: null, due: 'Sep 6' },

    // Phase 6 - Months 7-12 (LOCKED)
    { id: 'm25', t_en: 'Career path conversations',             t_id: 'Percakapan jalur karier',             cat: 'Growth',        phase: 6, dur: 50, status: 'locked', score: null, due: 'Oct 18' },
    { id: 'm26', t_en: 'Mentoring a new hire',                  t_id: 'Membimbing rekan baru',               cat: 'Growth',        phase: 6, dur: 60, status: 'locked', score: null, due: 'Dec 6' },
    { id: 'm27', t_en: 'Leading a project end-to-end',          t_id: 'Memimpin proyek end-to-end',          cat: 'Role',          phase: 6, dur: 90, status: 'locked', score: null, due: 'Jan 24' },
    { id: 'm28', t_en: 'Year-1 retrospective',                  t_id: 'Retrospektif tahun pertama',          cat: 'Growth',        phase: 6, dur: 45, status: 'locked', score: null, due: 'Mar 8' },
  ];

  // Active module's content items
  const ACTIVE_MODULE_CONTENT = [
    { id: 'c1', type: 'video', title_en: 'What inclusion looks like at work', title_id: 'Wujud inklusi di tempat kerja', source: 'SharePoint · Culture/2026', dur: '12:04', status: 'done' },
    { id: 'c2', type: 'video', title_en: 'Recognising unconscious bias',     title_id: 'Mengenali bias tak sadar',       source: 'SharePoint · Culture/2026', dur: '08:42', status: 'done' },
    { id: 'c3', type: 'doc',   title_en: 'Reporting procedures — read & sign', title_id: 'Prosedur pelaporan — baca & tanda tangan', source: 'SharePoint · HR/Policies', dur: '6 pages', status: 'done' },
    { id: 'c4', type: 'slides',title_en: 'Case studies — what would you do?', title_id: 'Studi kasus — apa yang Anda lakukan?', source: 'SharePoint · Culture/2026', dur: '14 slides', status: 'active' },
    { id: 'c5', type: 'doc',   title_en: 'Resources & where to get help',     title_id: 'Sumber daya & ke mana minta bantuan', source: 'SharePoint · HR/Policies', dur: '3 pages', status: 'todo' },
  ];

  // Quiz questions for the active module
  const QUIZ = [
    {
      q_en: 'A colleague repeatedly mispronounces your name despite gentle corrections. What is the most constructive first step?',
      q_id: 'Rekan kerja berulang kali salah mengucapkan nama Anda walau sudah dikoreksi. Langkah pertama yang paling konstruktif?',
      choices_en: [
        'Ignore it; it\'s a small thing.',
        'Speak with them directly and explain why it matters.',
        'Escalate to HR immediately.',
        'Stop using your real name at work.',
      ],
      choices_id: [
        'Abaikan saja; itu hal kecil.',
        'Bicarakan langsung dan jelaskan mengapa hal itu penting.',
        'Eskalasi ke HR segera.',
        'Berhenti memakai nama asli di kantor.',
      ],
      correct: 1,
    },
    {
      q_en: 'Which of these is an example of unconscious bias in hiring?',
      q_id: 'Mana yang merupakan contoh bias tak sadar dalam perekrutan?',
      choices_en: [
        'Asking every candidate the same role-relevant questions.',
        'Preferring candidates from universities you personally attended.',
        'Using a structured scoring rubric.',
        'Reviewing résumés with names removed.',
      ],
      choices_id: [
        'Menanyakan pertanyaan terkait peran yang sama ke semua kandidat.',
        'Lebih memilih kandidat dari universitas yang pernah Anda kunjungi.',
        'Memakai rubrik penilaian terstruktur.',
        'Meninjau CV tanpa nama.',
      ],
      correct: 1,
    },
    {
      q_en: 'You witness a colleague making an inappropriate joke about another team member\'s background. The other person looks uncomfortable. What should you do?',
      q_id: 'Anda melihat rekan kerja membuat lelucon tidak pantas tentang latar belakang rekan lain. Yang bersangkutan tampak tidak nyaman. Apa yang Anda lakukan?',
      choices_en: [
        'Wait until later to ask if they\'re okay; saying anything in the moment is too awkward.',
        'Speak up in the moment — calmly name the impact and move on.',
        'Laugh along so you don\'t embarrass the joker.',
        'Report anonymously and never mention it again.',
      ],
      choices_id: [
        'Tunggu nanti baru tanya apakah mereka baik-baik saja; bicara saat itu juga canggung.',
        'Bicara saat itu juga — sebutkan dampaknya dengan tenang lalu lanjutkan.',
        'Ikut tertawa supaya tidak mempermalukan yang bercanda.',
        'Laporkan anonim dan jangan disinggung lagi.',
      ],
      correct: 1,
    },
    {
      q_en: 'True or false: Reasonable accommodations under our policy must be requested in writing before any verbal discussion.',
      q_id: 'Benar atau salah: Akomodasi wajar menurut kebijakan kami harus diajukan tertulis sebelum diskusi lisan.',
      choices_en: ['True', 'False'],
      choices_id: ['Benar', 'Salah'],
      correct: 1,
    },
    {
      q_en: 'A manager tells a hire that "people like them tend to struggle with this project." This statement is best described as:',
      q_id: 'Atasan berkata ke rekan baru bahwa "orang seperti kamu biasanya kesulitan dengan proyek ini." Pernyataan ini paling tepat disebut:',
      choices_en: [
        'Honest feedback the hire should appreciate.',
        'A stereotype that is potentially discriminatory and worth reporting.',
        'Normal mentorship language.',
        'Not a workplace issue if said privately.',
      ],
      choices_id: [
        'Umpan balik jujur yang patut diapresiasi.',
        'Stereotip yang berpotensi diskriminatif dan layak dilaporkan.',
        'Bahasa pendampingan yang wajar.',
        'Bukan isu kantor jika diucapkan privat.',
      ],
      correct: 1,
    },
    {
      q_en: 'Which channel is the correct first stop for raising a concern about a peer-level interaction?',
      q_id: 'Saluran mana yang tepat untuk pertama kali mengangkat keprihatinan tentang interaksi antar rekan?',
      choices_en: [
        'Public Slack channel #general',
        'Your buddy or hiring manager',
        'External labour authority',
        'Company-wide all-hands meeting',
      ],
      choices_id: [
        'Channel Slack publik #general',
        'Buddy atau atasan langsung Anda',
        'Lembaga ketenagakerjaan eksternal',
        'Rapat all-hands seluruh perusahaan',
      ],
      correct: 1,
    },
    {
      q_en: 'Anonymous reporting through our channel is:',
      q_id: 'Pelaporan anonim melalui saluran kami adalah:',
      choices_en: [
        'Discouraged — we only investigate signed reports.',
        'Permitted; the company commits to investigate credible signals regardless of named reporter.',
        'Required for all reports.',
        'Available only to managers.',
      ],
      choices_id: [
        'Tidak dianjurkan — kami hanya selidiki laporan bernama.',
        'Diperbolehkan; perusahaan berkomitmen menyelidiki sinyal kredibel terlepas dari pelapor bernama.',
        'Wajib untuk semua laporan.',
        'Hanya tersedia untuk manajer.',
      ],
      correct: 1,
    },
    {
      q_en: 'A teammate from a different cultural background interprets your direct feedback as rude. The most useful response is to:',
      q_id: 'Rekan dari budaya berbeda menganggap umpan balik langsung Anda kasar. Respons paling berguna adalah:',
      choices_en: [
        'Insist directness is the only honest style and they need to adapt.',
        'Apologise and discuss communication preferences; calibrate together.',
        'Stop giving them feedback entirely.',
        'Only communicate via your manager going forward.',
      ],
      choices_id: [
        'Bersikeras bahwa lugas adalah satu-satunya gaya jujur dan mereka harus beradaptasi.',
        'Minta maaf dan diskusikan preferensi komunikasi; kalibrasi bersama.',
        'Hentikan memberi mereka umpan balik sama sekali.',
        'Komunikasi hanya lewat atasan ke depan.',
      ],
      correct: 1,
    },
    {
      q_en: 'When is retaliation against someone who raised an inclusion concern permitted?',
      q_id: 'Kapan pembalasan terhadap orang yang mengangkat keprihatinan inklusi diperbolehkan?',
      choices_en: [
        'When their report turned out to be unfounded.',
        'When the report damaged team morale.',
        'Never. Retaliation is itself a violation.',
        'Only with HR approval.',
      ],
      choices_id: [
        'Jika laporan ternyata tidak berdasar.',
        'Jika laporan merusak moral tim.',
        'Tidak pernah. Pembalasan adalah pelanggaran tersendiri.',
        'Hanya dengan persetujuan HR.',
      ],
      correct: 2,
    },
    {
      q_en: 'After completing this module, which behaviour change would your manager most expect to see?',
      q_id: 'Setelah modul ini, perubahan perilaku apa yang paling diharapkan atasan Anda?',
      choices_en: [
        'Avoiding all conversations about identity or background.',
        'Calling out bias in others while ignoring your own.',
        'Noticing your own assumptions and inviting feedback when you miss.',
        'Reporting every off-colour comment to HR by default.',
      ],
      choices_id: [
        'Menghindari semua percakapan tentang identitas atau latar belakang.',
        'Menyoroti bias orang lain sambil mengabaikan diri sendiri.',
        'Menyadari asumsi sendiri dan mengundang umpan balik ketika keliru.',
        'Melaporkan setiap komentar tidak elok ke HR secara default.',
      ],
      correct: 2,
    },
  ];

  // Up-next list inside the viewer
  const TRANSCRIPT = [
    { ts: '00:00', en: 'Welcome. Over the next twelve minutes we\'ll walk through what inclusion looks like — not as a policy, but as everyday behaviour.', id: 'Selamat datang. Dalam dua belas menit ke depan kita akan membahas wujud inklusi — bukan sebagai kebijakan, tetapi sebagai perilaku sehari-hari.' },
    { ts: '00:34', en: 'Inclusion is not the absence of conflict. It\'s the capacity to handle conflict without anyone shrinking themselves to fit in.', id: 'Inklusi bukan absennya konflik. Ini kapasitas menangani konflik tanpa ada yang harus mengecilkan diri agar pas.' },
    { ts: '01:18', en: 'We\'ll cover three patterns: the moment of feedback, the moment of disagreement, and the moment of error.', id: 'Kita akan bahas tiga pola: momen umpan balik, momen ketidaksetujuan, dan momen salah.' },
    { ts: '02:04', en: 'Let\'s start with feedback. Most discomfort in cross-cultural feedback comes from style mismatch, not content.', id: 'Mulai dari umpan balik. Sebagian besar ketidaknyamanan umpan balik lintas budaya datang dari ketidakcocokan gaya, bukan konten.' },
    { ts: '02:52', en: 'A direct style can read as harsh to someone used to indirect framing. An indirect style can read as evasive to a direct listener.', id: 'Gaya lugas terdengar kasar bagi yang terbiasa kerangka tidak langsung. Gaya tidak langsung terdengar mengelak bagi pendengar lugas.' },
    { ts: '03:40', en: 'The fix isn\'t to pick a winner. The fix is to name the style explicitly when you\'re calibrating with a new person.', id: 'Solusinya bukan memilih pemenang. Solusinya adalah menamai gaya secara eksplisit saat berkalibrasi dengan orang baru.' },
  ];

  // ============================================================
  //  EMPLOYEE ASSISTANT (v3.3 pillar) — categories, articles, conversation
  // ============================================================
  const ASSIST_T = {
    en: {
      assist_nav: 'Assistant',
      assist_eyebrow: 'Employee assistant',
      assist_title: 'Ask anything about HR, payroll, benefits, IT.',
      assist_sub: 'Grounded in your company\'s policies and onboarding modules. Every answer cites its source.',
      ask_placeholder: 'Ask in English or Bahasa — e.g. "how do I claim reimbursement for a laptop accessory?"',
      ask_anon: 'Ask anonymously',
      ask_anon_h: 'HR will see the question without your name. Escalation reply still comes back to you.',
      ask_send: 'Ask',
      ask_hr: 'Ask HR instead',
      escalate_h: 'Forward this conversation to the HR Ops queue — they respond within their SLA.',
      cite_l: 'Source',
      conf_high: 'High confidence',
      conf_partial: 'Partial match',
      hr_team: 'HR Ops · responds within SLA',
      thinking: 'Assistant is thinking',
      out_of_scope: 'Out of scope',
      route_handoff: 'Routed to HR',
      cat_label: 'Topics this assistant can help with',
      cat_in_title: 'In scope — answered with citation',
      cat_route_title: 'Routed — sensitive, needs a human',
      cat_out_title: 'Out of scope — go to a licensed channel',
      trending_l: 'Trending in your company this week',
      assist_history: 'Past conversations',
      new_conversation: 'New conversation',
      privacy_l: 'Privacy posture',
      privacy_h: 'Full text kept 90 days, then aggregate-only. Managers never see your conversations. PII auto-redacted.',
      session_started: 'Session started',
      thanks_feedback: 'Thanks — noted.',
      starter_prompts_l: 'Try one of these',
      open_module: 'Open the module',
      assist_btn_open: 'Open assistant',
      assist_floating: 'Ask assistant',
    },
    id: {
      assist_nav: 'Asisten',
      assist_eyebrow: 'Asisten karyawan',
      assist_title: 'Tanya apa saja tentang HR, gaji, tunjangan, IT.',
      assist_sub: 'Berbasis kebijakan perusahaan dan modul onboarding Anda. Setiap jawaban mencantumkan sumbernya.',
      ask_placeholder: 'Tanya dalam Indonesia atau Inggris — mis. "bagaimana cara klaim reimbursement laptop?"',
      ask_anon: 'Tanya anonim',
      ask_anon_h: 'HR melihat pertanyaan tanpa nama Anda. Balasan eskalasi tetap kembali ke Anda.',
      ask_send: 'Tanya',
      ask_hr: 'Tanyakan ke HR',
      escalate_h: 'Teruskan percakapan ini ke antrian HR Ops — mereka merespons sesuai SLA.',
      cite_l: 'Sumber',
      conf_high: 'Keyakinan tinggi',
      conf_partial: 'Cocok sebagian',
      hr_team: 'HR Ops · respons sesuai SLA',
      thinking: 'Asisten sedang berpikir',
      out_of_scope: 'Di luar cakupan',
      route_handoff: 'Diteruskan ke HR',
      cat_label: 'Topik yang dapat dibantu asisten ini',
      cat_in_title: 'Dalam cakupan — dijawab dengan kutipan',
      cat_route_title: 'Diteruskan — sensitif, butuh manusia',
      cat_out_title: 'Di luar cakupan — ke kanal berlisensi',
      trending_l: 'Trending di perusahaan Anda minggu ini',
      assist_history: 'Percakapan sebelumnya',
      new_conversation: 'Percakapan baru',
      privacy_l: 'Posisi privasi',
      privacy_h: 'Teks lengkap disimpan 90 hari, lalu agregat saja. Atasan tidak pernah melihat percakapan Anda. PII otomatis disensor.',
      session_started: 'Sesi dimulai',
      thanks_feedback: 'Terima kasih — dicatat.',
      starter_prompts_l: 'Coba salah satu ini',
      open_module: 'Buka modulnya',
      assist_btn_open: 'Buka asisten',
      assist_floating: 'Tanya asisten',
    }
  };

  // Topic scope per §16 of the blueprint — 7 IN, 2 ROUTE, 3 OUT
  const ASSIST_CATEGORIES = [
    // IN
    { id: 'hr',         scope: 'in',    icon: 'home',       label_en: 'HR Policy',           label_id: 'Kebijakan HR',           sample_en: 'How many annual leave days do I have?',           sample_id: 'Berapa hari cuti tahunan saya?',                          articles: 14 },
    { id: 'payroll',    scope: 'in',    icon: 'doc',        label_en: 'Payroll & Tax',       label_id: 'Gaji & Pajak',           sample_en: 'When is payday? How is NPWP applied?',            sample_id: 'Kapan tanggal gajian? Bagaimana NPWP diterapkan?',        articles: 9  },
    { id: 'benefits',   scope: 'in',    icon: 'medal',      label_en: 'Benefits & Insurance', label_id: 'Tunjangan & Asuransi',   sample_en: 'How do I claim BPJS for my dependent?',           sample_id: 'Bagaimana saya klaim BPJS untuk tanggungan?',             articles: 18 },
    { id: 'it',         scope: 'in',    icon: 'settings',   label_en: 'IT Support',          label_id: 'Bantuan IT',             sample_en: 'How do I connect to the VPN?',                    sample_id: 'Bagaimana saya terhubung ke VPN?',                        articles: 12 },
    { id: 'onboarding', scope: 'in',    icon: 'route',      label_en: 'Onboarding',          label_id: 'Onboarding',             sample_en: 'Where do I find my orientation schedule?',        sample_id: 'Di mana jadwal orientasi saya?',                          articles: 7  },
    { id: 'attendance', scope: 'in',    icon: 'clock',      label_en: 'Attendance',          label_id: 'Kehadiran',              sample_en: 'How do I submit a WFH request?',                  sample_id: 'Bagaimana saya mengajukan WFH?',                          articles: 6  },
    { id: 'reimburse',  scope: 'in',    icon: 'doc',        label_en: 'Reimbursement',       label_id: 'Reimbursement',          sample_en: 'How do I submit a transport claim?',              sample_id: 'Bagaimana saya klaim transportasi?',                      articles: 8  },
    // ROUTE
    { id: 'workplace',  scope: 'route', icon: 'flag',       label_en: 'Workplace concerns',  label_id: 'Keluhan kerja',          sample_en: '"I\'m experiencing harassment. What do I do?"',    sample_id: '"Saya mengalami pelecehan. Apa yang harus saya lakukan?"', articles: 0 },
    { id: 'career',     scope: 'route', icon: 'sparkle',    label_en: 'Career & performance', label_id: 'Karier & performa',     sample_en: '"How do I prepare for my probation review?"',     sample_id: '"Bagaimana persiapan untuk review probasi?"',             articles: 0 },
    // OUT
    { id: 'medical',    scope: 'out',   icon: 'help',       label_en: 'Medical & mental health', label_id: 'Medis & kesehatan mental', sample_en: '"I\'m not coping with work pressure."',     sample_id: '"Saya kesulitan menghadapi tekanan kerja."',              articles: 0 },
    { id: 'legal',      scope: 'out',   icon: 'lock',       label_en: 'Legal advice',         label_id: 'Nasihat hukum',          sample_en: '"Can the company fire me for X?"',                 sample_id: '"Bisakah perusahaan memecat saya karena X?"',             articles: 0 },
    { id: 'salary',     scope: 'out',   icon: 'doc',        label_en: 'Salary negotiation',   label_id: 'Negosiasi gaji',         sample_en: '"How do I argue for a higher offer?"',             sample_id: '"Bagaimana negosiasi penawaran yang lebih tinggi?"',      articles: 0 },
  ];

  // Trending questions this week — surfaced on the empty state
  const ASSIST_TRENDING = [
    { id: 't1', q_en: 'How do I claim BPJS Kesehatan for my newborn?',                 q_id: 'Bagaimana cara klaim BPJS Kesehatan untuk bayi baru lahir?',       cat: 'benefits',  count: 47, trend: '+18' },
    { id: 't2', q_en: 'Where do I download the resignation letter template?',          q_id: 'Di mana saya unduh template surat pengunduran diri?',              cat: 'hr',        count: 31, trend: '+12' },
    { id: 't3', q_en: 'Can I carry over unused annual leave into the next year?',      q_id: 'Bisakah cuti tahunan yang tidak terpakai dialihkan ke tahun depan?', cat: 'hr',     count: 28, trend: '+9'  },
    { id: 't4', q_en: 'How do I reset my VPN access from a new laptop?',               q_id: 'Bagaimana reset akses VPN dari laptop baru?',                      cat: 'it',        count: 24, trend: '+4'  },
    { id: 't5', q_en: 'What\'s the late-arrival policy after a delayed commute?',      q_id: 'Apa kebijakan keterlambatan setelah perjalanan tertunda?',         cat: 'attendance', count: 19, trend: '+3' },
  ];

  // Sample conversation — based on Budi's vignette from §3
  const ASSIST_CONVERSATION = [
    {
      role: 'user',
      anon: false,
      when: '14:22',
      text_en: 'How do I claim reimbursement for a laptop accessory I bought for work?',
      text_id: 'Bagaimana cara klaim reimbursement laptop accessory yang saya beli untuk kerja?',
    },
    {
      role: 'assistant',
      when: '14:22',
      confidence: 'high',
      text_en: 'Reimbursement for IT accessories (cables, hubs, peripherals, etc.) follows a three-step process:\n\n1. Get a digital receipt — vendor must include their NPWP and your full name on the invoice.\n2. Fill the IT Reimbursement form on SharePoint. Attach the receipt and a one-line business reason.\n3. Submit before the 25th of the month — claims submitted later are processed the following payroll cycle.\n\nCap per accessory is IDR 2,500,000. Higher amounts need pre-approval from your manager.',
      text_id: 'Reimbursement untuk aksesoris IT (kabel, hub, peripheral, dll.) mengikuti proses tiga langkah:\n\n1. Dapatkan kuitansi digital — vendor wajib mencantumkan NPWP dan nama lengkap Anda di tagihan.\n2. Isi form IT Reimbursement di SharePoint. Lampirkan kuitansi dan alasan bisnis satu baris.\n3. Kirim sebelum tanggal 25 setiap bulan — pengajuan lebih dari itu diproses di siklus payroll berikutnya.\n\nBatas per aksesoris adalah IDR 2.500.000. Nominal di atas itu butuh persetujuan dahulu dari atasan langsung Anda.',
      citations: [
        { name: 'IT Reimbursement Policy v3.2', sub: 'HR Ops · Last reviewed Jan 2026', url: 'sharepoint/policies/it-reimbursement-v3-2.pdf' },
        { name: 'Finance · Submission deadlines', sub: 'Finance · Last reviewed Feb 2026', url: 'sharepoint/finance/submission-cutoffs.pdf' },
      ],
      links: [
        { label_en: 'Open IT Reimbursement form', label_id: 'Buka form IT Reimbursement', url: 'sharepoint/forms/it-reimb' }
      ],
    },
    {
      role: 'user',
      anon: false,
      when: '14:23',
      text_en: 'What if the vendor\'s invoice doesn\'t have my name on it?',
      text_id: 'Bagaimana jika tagihan vendor tidak ada nama saya?',
    },
    {
      role: 'assistant',
      when: '14:23',
      confidence: 'partial',
      text_en: 'Most vendors will issue a corrected invoice on request — that\'s the cleanest path. If they refuse (some smaller vendors do), Finance accepts the original invoice plus a signed proof-of-purchase form. The form is on SharePoint under Finance → Templates.\n\nI\'m less confident about edge cases like online marketplaces where the seller is anonymous — you may want HR to confirm before submitting.',
      text_id: 'Sebagian besar vendor akan menerbitkan ulang tagihan jika diminta — itu jalur paling bersih. Jika menolak (beberapa vendor kecil begitu), Finance menerima tagihan asli plus form bukti pembelian yang ditandatangani. Formnya ada di SharePoint di Finance → Templates.\n\nSaya kurang yakin untuk kasus tepi seperti marketplace online dengan penjual anonim — sebaiknya konfirmasi ke HR sebelum kirim.',
      citations: [
        { name: 'Finance · Proof-of-purchase template', sub: 'Finance · Last reviewed Dec 2025', url: 'sharepoint/finance/proof-template.pdf' },
      ],
    },
  ];

  // Previous conversations — left rail history
  const ASSIST_HISTORY = [
    { id: 'h1', title_en: 'IT reimbursement steps',                title_id: 'Langkah reimbursement IT',            when: 'Today, 14:22',  turns: 4, resolved: true,  cat: 'reimburse'  },
    { id: 'h2', title_en: 'BPJS dependents add — newborn',         title_id: 'Tambah tanggungan BPJS — bayi baru',  when: 'Yesterday',     turns: 5, resolved: true,  cat: 'benefits'   },
    { id: 'h3', title_en: 'Probation review preparation',          title_id: 'Persiapan review probasi',            when: '3 days ago',    turns: 3, resolved: false, cat: 'career', escalated: true },
    { id: 'h4', title_en: 'WFH submission cutoff',                 title_id: 'Batas pengajuan WFH',                 when: 'Mar 14',        turns: 2, resolved: true,  cat: 'attendance' },
    { id: 'h5', title_en: 'Annual leave carry-over rules',         title_id: 'Aturan pengalihan cuti tahunan',      when: 'Mar 11',        turns: 4, resolved: true,  cat: 'hr'         },
    { id: 'h6', title_en: 'VPN setup on new MacBook',              title_id: 'Setup VPN di MacBook baru',           when: 'Mar 9 · Day 1', turns: 2, resolved: true,  cat: 'it'         },
  ];

  // Starter prompts shown on empty state
  const ASSIST_STARTERS = [
    { q_en: 'When is my next payday and how do I read my payslip?',          q_id: 'Kapan gajian berikutnya dan bagaimana baca slip gaji?',     cat: 'payroll'  },
    { q_en: 'How do I add my newborn to BPJS Kesehatan?',                    q_id: 'Bagaimana menambahkan bayi ke BPJS Kesehatan?',             cat: 'benefits' },
    { q_en: 'What\'s the dress code for client-facing days?',                q_id: 'Apa dress code untuk hari client-facing?',                  cat: 'hr'       },
    { q_en: 'Where do I file a transport reimbursement claim?',              q_id: 'Di mana saya ajukan klaim reimbursement transport?',        cat: 'reimburse' },
    { q_en: 'How do I reset my VPN access from a new laptop?',               q_id: 'Bagaimana reset akses VPN dari laptop baru?',               cat: 'it'       },
    { q_en: 'Can I take next Friday as personal leave?',                     q_id: 'Bisakah saya ambil cuti pribadi Jumat depan?',              cat: 'attendance' },
  ];

  // ============================================================
  //  ASSESSMENTS — 7 psychological instruments across 4 milestones
  //  Source: Onboarding Assessment Guide v9 · Mei 2026
  //  Maya is at Day 22 → Pre-Day 1 + Day 7 done, Day 30 upcoming, Day 60 locked
  // ============================================================
  const ASSESS_T = {
    en: {
      asx_eyebrow: 'Developmental · not evaluative',
      asx_title: 'Your onboarding ',
      asx_title_em: 'assessments.',
      asx_sub: 'Seven psychological instruments across the first 60 days. None of them are pass/fail — every result belongs to you first, then your manager. They never enter your performance record.',
      asx_principle_l: 'How we use these',
      asx_p1_t: 'Not for grading',
      asx_p1_b: 'No "pass" or "fail". No ranking between hires. Every profile carries its own strengths and growth areas.',
      asx_p2_t: 'Unlocks context',
      asx_p2_b: 'Results give context on how you communicate, handle conflict, and collaborate — information that usually takes 3–6 months to surface naturally.',
      asx_p3_t: 'Yours first',
      asx_p3_b: 'You always read your report before HR shares anything with your manager. HR uses the data to support — not to evaluate or compare.',
      asx_p4_t: 'Confidential',
      asx_p4_b: 'Psychological reports are accessed only by HR and your direct manager. Not part of your formal performance file. Never used for promotion or termination decisions.',
      asx_progress_l: 'Onboarding assessment progress',
      asx_track: 'Track',
      asx_milestones: 'Milestones',
      asx_total_items: 'Total items',
      asx_minutes_spent: 'Minutes invested',
      asx_status_done: 'Complete',
      asx_status_now: 'Available now',
      asx_status_upcoming: 'Upcoming',
      asx_status_locked: 'Locked',
      asx_status_optional: 'Leadership track only',
      asx_start: 'Start assessment',
      asx_resume: 'Resume',
      asx_view_result: 'View result',
      asx_what: 'What it measures',
      asx_why: 'Why now',
      asx_youget: 'What you receive',
      asx_hrdoes: 'What HR does',
      asx_caveat: 'Reliability note',
      asx_ref: 'Reference',
      asx_items: 'items',
      asx_minutes: 'min',
      asx_outputs: 'outputs',
      asx_milestone_l: 'Milestone',
      asx_back_list: 'Back to assessments',
      asx_take_now: 'Take this assessment',
      asx_top_results: 'Your top results',
      asx_caveat_strong: 'Important caveat',
      asx_dev_only: 'Developmental purposes only — not used in selection, promotion, or termination decisions.',
      asx_share_l: 'Sharing',
      asx_share_v: 'You + your manager + HR. Never in your personnel file.',
      asx_pending: 'Available · please complete this week',
      asx_milestone_pre: 'Pre-Day 1',
      asx_milestone_d7: 'Day 7',
      asx_milestone_d30: 'Day 30',
      asx_milestone_d60: 'Day 60',
      asx_milestone_pre_l: 'Self-introduction',
      asx_milestone_d7_l: 'Team integration',
      asx_milestone_d30_l: 'Strengths mapping',
      asx_milestone_d60_l: 'Leadership coaching',
    },
    id: {
      asx_eyebrow: 'Pengembangan · bukan evaluasi',
      asx_title: 'Asesmen ',
      asx_title_em: 'onboarding Anda.',
      asx_sub: 'Tujuh instrumen psikologis sepanjang 60 hari pertama. Tidak ada yang lulus/gagal — setiap hasil milik Anda dulu, lalu atasan langsung. Tidak pernah masuk ke catatan kinerja formal.',
      asx_principle_l: 'Bagaimana kami menggunakannya',
      asx_p1_t: 'Bukan untuk menilai',
      asx_p1_b: 'Tidak ada "lulus" atau "tidak lulus". Tidak ada peringkat antar karyawan. Setiap profil punya kekuatan dan area pengembangannya sendiri.',
      asx_p2_t: 'Membuka konteks',
      asx_p2_b: 'Hasil memberi konteks pada cara Anda berkomunikasi, menangani konflik, dan berkolaborasi — informasi yang biasanya butuh 3–6 bulan untuk muncul alami.',
      asx_p3_t: 'Milik Anda dulu',
      asx_p3_b: 'Anda selalu membaca laporan sebelum HR meneruskan ke atasan. HR memakai data untuk mendukung — bukan mengevaluasi atau membandingkan.',
      asx_p4_t: 'Rahasia',
      asx_p4_b: 'Laporan psikologis hanya diakses HR dan atasan langsung. Bukan bagian dari catatan kinerja formal. Tidak pernah dipakai untuk promosi atau pemutusan.',
      asx_progress_l: 'Progres asesmen onboarding',
      asx_track: 'Jalur',
      asx_milestones: 'Tonggak',
      asx_total_items: 'Total item',
      asx_minutes_spent: 'Menit yang dihabiskan',
      asx_status_done: 'Selesai',
      asx_status_now: 'Tersedia sekarang',
      asx_status_upcoming: 'Mendatang',
      asx_status_locked: 'Terkunci',
      asx_status_optional: 'Hanya jalur kepemimpinan',
      asx_start: 'Mulai asesmen',
      asx_resume: 'Lanjutkan',
      asx_view_result: 'Lihat hasil',
      asx_what: 'Yang diukur',
      asx_why: 'Mengapa sekarang',
      asx_youget: 'Yang Anda terima',
      asx_hrdoes: 'Yang dilakukan HR',
      asx_caveat: 'Catatan reliabilitas',
      asx_ref: 'Referensi',
      asx_items: 'item',
      asx_minutes: 'mnt',
      asx_outputs: 'output',
      asx_milestone_l: 'Tonggak',
      asx_back_list: 'Kembali ke asesmen',
      asx_take_now: 'Kerjakan asesmen ini',
      asx_top_results: 'Hasil utama Anda',
      asx_caveat_strong: 'Catatan penting',
      asx_dev_only: 'Hanya untuk pengembangan — tidak dipakai dalam keputusan seleksi, promosi, atau pemutusan.',
      asx_share_l: 'Pembagian',
      asx_share_v: 'Anda + atasan langsung + HR. Tidak pernah di catatan personalia.',
      asx_pending: 'Tersedia · mohon selesaikan minggu ini',
      asx_milestone_pre: 'Pre-Day 1',
      asx_milestone_d7: 'Hari 7',
      asx_milestone_d30: 'Hari 30',
      asx_milestone_d60: 'Hari 60',
      asx_milestone_pre_l: 'Pengenalan diri',
      asx_milestone_d7_l: 'Integrasi tim',
      asx_milestone_d30_l: 'Pemetaan kekuatan',
      asx_milestone_d60_l: 'Coaching kepemimpinan',
    }
  };

  const ASSESSMENTS = [
    {
      id: 'a1',
      seq: '01',
      milestone: 'pre',
      milestoneDay: 'Pre-Day 1',
      color: 'forest',
      ref: 'Insights Discovery® / Jungian Typology',
      title_en: 'Work Personality Profile (4 Colours)',
      title_id: 'Profil Kepribadian Kerja (4 Warna)',
      tagline_en: 'Communication and work-style preference mapped to four colour energies',
      tagline_id: 'Pemetaan preferensi komunikasi dan kerja ke empat warna energi',
      items: 72,
      itemsLabel_en: 'paired items',
      itemsLabel_id: 'item berpasangan',
      minutes: 15,
      outputs: 8,
      outputsLabel_en: 'profile types',
      outputsLabel_id: 'tipe profil',
      status: 'done',
      doneOn_en: 'Mar 6 · 2 days before Day 1',
      doneOn_id: '6 Mar · 2 hari sebelum Hari 1',
      what_en: 'Jungian preferences on three dimensions — Extraversion/Introversion (E/I), Thinking/Feeling (T/F), Sensing/Intuition (S/N) — mapped to four colour energies: Red (Influence), Yellow (Inspiration), Green (Support), Blue (Analysis).',
      what_id: 'Preferensi Jungian pada tiga dimensi — Ekstraversi/Introversi (E/I), Berpikir/Perasaan (T/F), Penginderaan/Intuisi (S/N) — dipetakan ke empat warna energi: Merah (Pengaruh), Kuning (Inspirasi), Hijau (Dukungan), Biru (Analisis).',
      why_en: 'Lets your manager adjust the Day-1 welcome, the format of your first 1-on-1, and how the team is introduced — based on your communication preference. Cuts down on the misinterpretation that typically marks week one.',
      why_id: 'Memungkinkan atasan menyesuaikan welcome Day 1, format 1-on-1 pertama, dan cara perkenalan tim — berdasarkan preferensi komunikasi Anda. Mengurangi miskomunikasi yang biasanya menandai minggu pertama.',
      youget_en: 'Dominant + secondary colour, a one-page description of your preferred work style, and collaboration tips for engaging with other profiles.',
      youget_id: 'Warna dominan + sekunder, deskripsi satu halaman gaya kerja preferensial Anda, dan tips kolaborasi dengan profil lain.',
      hrdoes_en: 'Forwards the profile summary to your direct manager before Day 1. Used to: (1) prepare your team introduction, (2) pair you with a buddy whose profile complements yours, (3) adjust the orientation cadence in week 1.',
      hrdoes_id: 'Meneruskan ringkasan profil ke atasan sebelum Day 1. Digunakan untuk: (1) menyiapkan perkenalan tim, (2) memasangkan dengan buddy yang melengkapi profil, (3) menyesuaikan ritme orientasi minggu pertama.',
      caveat_en: 'Inspired by the Insights Discovery® construct (Insights Learning & Development Ltd) — not the official instrument. Personality profiles are stable, but do not describe competence or performance. Not to be used in selection decisions.',
      caveat_id: 'Terinspirasi konstruksi Insights Discovery® (Insights Learning & Development Ltd) — bukan instrumen resmi. Profil kepribadian stabil, namun tidak menggambarkan kompetensi atau kinerja. Tidak untuk keputusan seleksi.',
      result: {
        primary_en: 'Cool Blue · Analysis',
        primary_id: 'Biru Dingin · Analisis',
        secondary_en: 'Earth Green · Support',
        secondary_id: 'Hijau Bumi · Dukungan',
        primaryPct: 38,
        bars: [
          { k_en: 'Cool Blue · Analysis',  k_id: 'Biru Dingin · Analisis',   v: 38, color: '#2147A1' },
          { k_en: 'Earth Green · Support', k_id: 'Hijau Bumi · Dukungan',    v: 31, color: '#0A6E5C' },
          { k_en: 'Sunshine Yellow · Inspire', k_id: 'Kuning Mentari · Inspirasi', v: 18, color: '#D4A93C' },
          { k_en: 'Fiery Red · Influence', k_id: 'Merah Api · Pengaruh',     v: 13, color: '#A1361F' },
        ],
        summary_en: 'A reflective, structured worker who prefers thinking through complete ideas before sharing. Comfortable with detail, cautious with snap decisions. Pairs naturally with verbal extroverts as a balancing force.',
        summary_id: 'Pekerja reflektif dan terstruktur yang lebih suka memikirkan ide secara utuh sebelum berbagi. Nyaman dengan detail, hati-hati dengan keputusan cepat. Berpasangan alami dengan ekstrovert verbal sebagai penyeimbang.',
      }
    },
    {
      id: 'a2',
      seq: '02',
      milestone: 'pre',
      milestoneDay: 'Pre-Day 1',
      color: 'forest',
      ref: 'Thomas-Kilmann Conflict Mode Instrument® / TKI',
      title_en: 'Conflict-Handling Mode Profile',
      title_id: 'Profil Mode Penanganan Konflik',
      tagline_en: 'Default interpersonal conflict response across five modes',
      tagline_id: 'Kecenderungan penanganan konflik antarpribadi dalam lima mode',
      items: 30,
      itemsLabel_en: 'paired items',
      itemsLabel_id: 'item berpasangan',
      minutes: 10,
      outputs: 5,
      outputsLabel_en: 'conflict modes',
      outputsLabel_id: 'mode konflik',
      status: 'done',
      doneOn_en: 'Mar 7 · 1 day before Day 1',
      doneOn_id: '7 Mar · 1 hari sebelum Hari 1',
      what_en: 'Five conflict-handling styles on two dimensions (assertiveness × cooperation): Competing, Collaborating, Compromising, Avoiding, Accommodating.',
      what_id: 'Lima gaya penanganan konflik pada dua dimensi (asertivitas × kooperasi): Bersaing, Berkolaborasi, Berkompromi, Menghindari, Mengakomodasi.',
      why_en: 'Conflict is unavoidable on a new team — everyone hits it, and people handle it differently. Knowing your default style helps your manager anticipate early-conflict reactions (e.g. an "Avoiding" hire may seem to agree while privately resisting).',
      why_id: 'Konflik tak terhindarkan di tim baru — semua mengalaminya, dan setiap orang menanganinya beda. Mengetahui gaya default Anda membantu atasan mengantisipasi reaksi konflik awal (mis. yang "Menghindari" tampak setuju padahal pasif-resisten).',
      youget_en: 'Five-mode scores on a 0–12 scale, with one or two dominant modes explained in context: when the style works, when it backfires.',
      youget_id: 'Skor lima mode pada skala 0–12, dengan satu atau dua mode dominan dijelaskan secara kontekstual: kapan efektif, kapan jadi bumerang.',
      hrdoes_en: 'Shares the profile to your manager alongside your Personality profile. Used for: (1) choosing the right approach when giving early feedback, (2) drafting team communication norms, (3) as a reflection topic in your first 1-on-1.',
      hrdoes_id: 'Meneruskan profil ke atasan bersama Profil Kepribadian. Berguna untuk: (1) memilih pendekatan saat memberi umpan balik awal, (2) menyusun aturan komunikasi tim, (3) sebagai topik refleksi di 1-on-1 minggu pertama.',
      caveat_en: 'Adapted from the Thomas-Kilmann Conflict Mode Instrument® (CPP, Inc.) — not an official administration. Norms are indicative (general-population averages), not yet validated on Indonesian workers.',
      caveat_id: 'Mengadaptasi Thomas-Kilmann Conflict Mode Instrument® (CPP, Inc.) — bukan administrasi resmi. Norma indikatif (rata-rata populasi umum), belum tervalidasi pada pekerja Indonesia.',
      result: {
        primary_en: 'Collaborating',
        primary_id: 'Berkolaborasi',
        secondary_en: 'Avoiding',
        secondary_id: 'Menghindari',
        primaryPct: 10,
        bars: [
          { k_en: 'Collaborating',   k_id: 'Berkolaborasi',  v: 10, color: '#0A6E5C' },
          { k_en: 'Avoiding',        k_id: 'Menghindari',    v: 8,  color: '#5C8FA8' },
          { k_en: 'Compromising',    k_id: 'Berkompromi',    v: 6,  color: '#8A6A1F' },
          { k_en: 'Accommodating',   k_id: 'Mengakomodasi',  v: 4,  color: '#7C8A78' },
          { k_en: 'Competing',       k_id: 'Bersaing',       v: 2,  color: '#A1361F' },
        ],
        summary_en: 'Strongly collaborative — looks for outcomes where everyone wins, but may avoid surface-level disagreements until they accumulate. Coach toward voicing dissent earlier; reward incremental candour.',
        summary_id: 'Sangat kolaboratif — mencari hasil yang menguntungkan semua, namun cenderung menghindari ketidaksepakatan permukaan sampai menumpuk. Latih untuk menyuarakan keberatan lebih awal; apresiasi kejujuran bertahap.',
      }
    },
    {
      id: 'a3',
      seq: '03',
      milestone: 'd7',
      milestoneDay: 'Day 7',
      color: 'cobalt',
      ref: 'Belbin Team Roles®',
      title_en: 'Team Role Inventory',
      title_id: 'Inventori Peran Tim',
      tagline_en: 'Mapping of natural contribution roles within team dynamics',
      tagline_id: 'Pemetaan peran kontribusi alami dalam dinamika tim',
      items: 63,
      itemsLabel_en: 'forced-rank items',
      itemsLabel_id: 'item peringkat paksa',
      minutes: 15,
      outputs: 9,
      outputsLabel_en: 'team roles',
      outputsLabel_id: 'peran tim',
      status: 'done',
      doneOn_en: 'Mar 16 · Day 7 morning',
      doneOn_id: '16 Mar · pagi Hari 7',
      what_en: 'Nine contribution roles grouped into three orientations: Action (Shaper, Implementer, Completer Finisher), People (Coordinator, Teamworker, Resource Investigator), Thinking (Plant, Monitor Evaluator, Specialist). Forced-ranking via 10-point distribution per section.',
      what_id: 'Sembilan peran kontribusi dikelompokkan ke tiga orientasi: Tindakan (Shaper, Implementer, Completer Finisher), Manusia (Coordinator, Teamworker, Resource Investigator), Pemikiran (Plant, Monitor Evaluator, Specialist). Forced-ranking via distribusi 10 poin per seksi.',
      why_en: 'Day 7 is the right window — you have first impressions of your team without rigid patterns yet. Results help your manager decide initial responsibilities: which roles are already filled (so you can complement), which are open (where you can take space).',
      why_id: 'Day 7 adalah waktu tepat — Anda sudah punya impresi awal tim tapi belum mengembangkan pola kaku. Hasil membantu atasan menentukan tanggung jawab awal: peran apa yang sudah ada (Anda bisa melengkapi), peran apa yang masih kosong (Anda bisa mengambil ruang).',
      youget_en: 'Scores for all 9 roles, identification of your Top 3 dominant roles with strengths and "allowable weaknesses" for each, plus a cluster analysis of which orientation dominates (Action / People / Thinking).',
      youget_id: 'Skor 9 peran, identifikasi Top 3 peran dominan dengan kekuatan dan "kelemahan yang diperbolehkan" untuk masing-masing, plus analisis klaster orientasi (Tindakan / Manusia / Pemikiran).',
      hrdoes_en: 'Shares Top 3 roles with your manager. Used to: (1) map team contribution as a whole when adding a new member, (2) select early projects matching your dominant roles, (3) discuss your "allowable weaknesses" in 1-on-1 to build self-awareness.',
      hrdoes_id: 'Meneruskan Top 3 peran ke atasan. Digunakan untuk: (1) memetakan kontribusi tim ketika anggota baru bergabung, (2) memilih proyek awal yang cocok dengan peran dominan, (3) membahas "kelemahan yang diperbolehkan" di 1-on-1 untuk membangun kesadaran diri.',
      caveat_en: 'Adapted from the Belbin Team Roles Self-Perception Inventory® (Belbin Associates Ltd) — not an official administration. At Day 7 you may answer from your previous team experience rather than the current team — that\'s expected and still valid as a preference profile.',
      caveat_id: 'Mengadaptasi Belbin Team Roles Self-Perception Inventory® (Belbin Associates Ltd) — bukan administrasi resmi. Pada Day 7 Anda mungkin menjawab dari pengalaman tim sebelumnya, bukan tim saat ini — itu wajar dan tetap valid sebagai profil preferensi.',
      result: {
        primary_en: 'Monitor Evaluator',
        primary_id: 'Monitor Evaluator',
        secondary_en: 'Completer Finisher',
        secondary_id: 'Completer Finisher',
        primaryPct: 19,
        bars: [
          { k_en: 'Monitor Evaluator',     k_id: 'Monitor Evaluator',     v: 19, color: '#2147A1' },
          { k_en: 'Completer Finisher',    k_id: 'Completer Finisher',    v: 17, color: '#2147A1' },
          { k_en: 'Specialist',            k_id: 'Specialist',            v: 14, color: '#2147A1' },
          { k_en: 'Implementer',           k_id: 'Implementer',           v: 12, color: '#5C8FA8' },
          { k_en: 'Teamworker',            k_id: 'Teamworker',            v: 11, color: '#5C8FA8' },
          { k_en: 'Plant',                 k_id: 'Plant',                 v: 9,  color: '#7C8A78' },
          { k_en: 'Coordinator',           k_id: 'Coordinator',           v: 7,  color: '#7C8A78' },
          { k_en: 'Resource Investigator', k_id: 'Resource Investigator', v: 6,  color: '#7C8A78' },
          { k_en: 'Shaper',                k_id: 'Shaper',                v: 5,  color: '#A1361F' },
        ],
        summary_en: 'Thinking-orientation dominant. A sober, analytical contributor who works through problems carefully and finishes what they start. Complements teams with strong Shapers or Resource Investigators who drive momentum.',
        summary_id: 'Orientasi Pemikiran dominan. Kontributor analitis yang tenang, memproses masalah dengan hati-hati dan menyelesaikan apa yang dimulai. Melengkapi tim dengan Shaper atau Resource Investigator kuat yang mendorong momentum.',
      }
    },
    {
      id: 'a4',
      seq: '04',
      milestone: 'd7',
      milestoneDay: 'Day 7',
      color: 'cobalt',
      ref: 'EQ-i 2.0® / Multi-Health Systems Inc.',
      title_en: 'Emotional Intelligence Profile',
      title_id: 'Profil Kecerdasan Emosional',
      tagline_en: '15 EQ subscales across 5 composites',
      tagline_id: 'Pemetaan 15 subskala EQ dalam 5 komposit',
      items: 90,
      itemsLabel_en: 'Likert items',
      itemsLabel_id: 'item Likert',
      minutes: 20,
      outputs: 15,
      outputsLabel_en: 'subscales',
      outputsLabel_id: 'subskala',
      status: 'done',
      doneOn_en: 'Mar 16 · Day 7 afternoon',
      doneOn_id: '16 Mar · sore Hari 7',
      what_en: 'Five composites (Self-Perception, Self-Expression, Interpersonal, Decision Making, Stress Management), each with 3 subscales — 15 EQ areas total. Scored on the Myralix EQ scale (0–100%), not the official EQ-i 2.0 Standard Score.',
      what_id: 'Lima komposit (Persepsi Diri, Ekspresi Diri, Interpersonal, Pengambilan Keputusan, Manajemen Stres), masing-masing 3 subskala — total 15 area EQ. Skor pada Skala Myralix EQ (0–100%), bukan Standard Score EQ-i 2.0 resmi.',
      why_en: 'Week one is high-stress — new context, pressure to prove yourself, ambiguity. The EQ profile shows where you tend to be strong and where you may need support. Important for: your manager choosing how hard to push early tasks, and you for self-awareness.',
      why_id: 'Minggu pertama tinggi stres — konteks baru, tekanan untuk membuktikan diri, ketidakpastian. Profil EQ menunjukkan area kuat dan area yang butuh dukungan. Penting untuk: atasan memilih intensitas tugas awal, dan Anda untuk self-awareness.',
      youget_en: 'Scores for the 5 composites + 15 subscales visualised, identification of your top 3 strengths and 3 priority growth areas, plus suggested practices for each.',
      youget_id: 'Skor 5 komposit + 15 subskala dengan visualisasi, identifikasi 3 kekuatan teratas dan 3 area pengembangan prioritas, plus latihan untuk masing-masing.',
      hrdoes_en: 'Combines this with your Conflict profile to give your manager a comprehensive picture of working style and the support you may need. The Stress Management composite is especially important for early conversations about workload expectations.',
      hrdoes_id: 'Mengkombinasikan dengan profil Mode Konflik untuk memberi gambaran komprehensif kepada atasan tentang gaya kerja dan dukungan yang Anda butuhkan. Komposit "Manajemen Stres" penting untuk diskusi ekspektasi beban kerja awal.',
      caveat_en: 'Myralix EQ scores (0–100%) are not equivalent to official EQ-i 2.0 Standard Scores. Short form: 90 items (official: 133). Use for profile signals, not clinical scoring. The Well-Being (Happiness) indicator is not included.',
      caveat_id: 'Skor Myralix EQ (0–100%) tidak setara dengan Standard Score EQ-i 2.0 resmi. Versi singkat 90 item (resmi: 133). Untuk gambaran profil, bukan skor klinis. Indikator Well-Being (Happiness) tidak dimasukkan.',
      result: {
        primary_en: 'Interpersonal · 78%',
        primary_id: 'Interpersonal · 78%',
        secondary_en: 'Self-Perception · 71%',
        secondary_id: 'Persepsi Diri · 71%',
        primaryPct: 78,
        bars: [
          { k_en: 'Interpersonal',       k_id: 'Interpersonal',         v: 78, color: '#2147A1' },
          { k_en: 'Self-Perception',     k_id: 'Persepsi Diri',         v: 71, color: '#2147A1' },
          { k_en: 'Decision Making',     k_id: 'Pengambilan Keputusan', v: 68, color: '#5C8FA8' },
          { k_en: 'Self-Expression',     k_id: 'Ekspresi Diri',         v: 54, color: '#8A6A1F' },
          { k_en: 'Stress Management',   k_id: 'Manajemen Stres',       v: 49, color: '#A1361F' },
        ],
        summary_en: 'Strong on relating to others and self-awareness. Stress Management is a growth area — particularly Flexibility and Impulse Control. Discuss workload pacing in your next 1-on-1; small wins on Stress Management compound quickly.',
        summary_id: 'Kuat dalam relasi antarpribadi dan kesadaran diri. Manajemen Stres adalah area pengembangan — terutama Fleksibilitas dan Kontrol Impuls. Bahas pacing beban kerja di 1-on-1 berikutnya; kemenangan kecil di Manajemen Stres berlipat cepat.',
      }
    },
    {
      id: 'a5',
      seq: '05',
      milestone: 'd30',
      milestoneDay: 'Day 30',
      color: 'amethyst',
      ref: 'CliftonStrengths® / Gallup, Inc.',
      title_en: '34 Strengths Themes Inventory',
      title_id: 'Inventori 34 Tema Kekuatan',
      tagline_en: 'Natural talent themes across four work domains',
      tagline_id: 'Pemetaan tema bakat alami dalam empat domain kerja',
      items: 68,
      itemsLabel_en: 'paired-choice items',
      itemsLabel_id: 'item pasangan',
      minutes: 18,
      outputs: 34,
      outputsLabel_en: 'talent themes',
      outputsLabel_id: 'tema bakat',
      status: 'available',
      dueOn_en: 'Available now · please complete by Apr 8',
      dueOn_id: 'Tersedia sekarang · mohon selesaikan paling lambat 8 April',
      what_en: 'Thirty-four natural talent themes across four domains: Executing (9 themes), Influencing (8), Relationship Building (9), Strategic Thinking (8). Paired-choice format (forced ranking).',
      what_id: 'Tiga puluh empat tema bakat alami di empat domain: Eksekusi (9 tema), Pengaruh (8), Hubungan (9), Pemikiran Strategis (8). Format pilihan berpasangan (forced ranking).',
      why_en: 'Day 30 is the right window — you\'ve had enough experience in the role to reflect accurately. Identifying your Top 5 strengths helps you build a 90-day development plan focused on maximising strengths, not patching weaknesses.',
      why_id: 'Day 30 adalah waktu tepat — Anda sudah cukup pengalaman di peran baru untuk merefleksikan secara akurat. Identifikasi Top 5 kekuatan membantu menyusun rencana pengembangan 90 hari yang fokus memaksimalkan kekuatan, bukan menambal kelemahan.',
      youget_en: 'Top 5 talent themes with deep descriptions (how they work, when most productive, watch-out areas), domain distribution, and the full ranking of all 34 themes with a reliability note on mid-rank positions.',
      youget_id: 'Top 5 tema kekuatan dengan deskripsi mendalam (cara kerja, kapan paling produktif, area kewaspadaan), distribusi domain, dan peringkat lengkap 34 tema dengan catatan reliabilitas peringkat menengah.',
      hrdoes_en: 'Facilitates a 1-on-1 discussion between you and your manager using your Top 5 as the starting point. Key question: "How can we use these 5 strengths in your role over the next 3 months?" Avoids focusing on themes #6–34 as a basis for formal decisions.',
      hrdoes_id: 'Memfasilitasi diskusi 1-on-1 antara Anda dan atasan menggunakan Top 5 sebagai titik awal. Pertanyaan kunci: "Bagaimana kita bisa menggunakan 5 kekuatan ini di peran Anda dalam 3 bulan ke depan?" Menghindari fokus pada tema 6–34 sebagai dasar keputusan formal.',
      caveat_en: 'Short form: 68 items (official: 177). Top-5 themes are reliable for development; the mid-range (themes 6–34) carries a larger margin of error. Differences between mid-rank themes (e.g. #12 vs #15) are not statistically significant.',
      caveat_id: 'Versi singkat 68 item (resmi: 177). Top-5 tema reliabel untuk pengembangan; peringkat menengah (tema 6–34) memiliki margin error lebih besar. Perbedaan antar tema peringkat menengah (mis. #12 vs #15) tidak signifikan secara statistik.',
    },
    {
      id: 'a6',
      seq: '06',
      milestone: 'd30',
      milestoneDay: 'Day 30',
      color: 'amethyst',
      ref: 'Five Dysfunctions of a Team / Patrick Lencioni',
      title_en: 'Team Health Diagnostic',
      title_id: 'Diagnostik Kesehatan Tim',
      tagline_en: 'Reflection on integration impressions across the 5-layer team pyramid',
      tagline_id: 'Refleksi kesan integrasi pada lima lapisan piramida kesehatan tim',
      items: 15,
      itemsLabel_en: 'Likert items',
      itemsLabel_id: 'item Likert',
      minutes: 8,
      outputs: 5,
      outputsLabel_en: 'pyramid layers',
      outputsLabel_id: 'lapisan piramida',
      status: 'available',
      dueOn_en: 'Available now · please complete by Apr 8',
      dueOn_id: 'Tersedia sekarang · mohon selesaikan paling lambat 8 April',
      what_en: 'Your assessment of team health across the five Lencioni layers (bottom-up): Trust → Productive Conflict → Commitment → Accountability → Collective Results.',
      what_id: 'Penilaian Anda terhadap kesehatan tim di lima lapisan piramida Lencioni (dari dasar ke puncak): Kepercayaan → Konflik Produktif → Komitmen → Akuntabilitas → Hasil Kolektif.',
      why_en: 'New hires often see team dynamics with fresh eyes — you haven\'t internalised the compromises and assumptions long-tenured members carry. Your scores can be an early signal of structural issues that need attention.',
      why_id: 'Karyawan baru sering melihat dinamika tim dengan mata segar — Anda belum terbiasa kompromi dan asumsi yang dimiliki anggota lama. Skor Anda bisa jadi sinyal awal masalah struktural yang perlu ditangani.',
      youget_en: 'Scores for all 5 layers visualised as a pyramid, identification of the weakest layer as the team\'s development priority, and a reflective notes space.',
      youget_id: 'Skor 5 lapisan dengan visualisasi piramida, identifikasi lapisan terlemah sebagai prioritas pengembangan tim, dan ruang catatan reflektif.',
      hrdoes_en: 'Discusses results privately with your manager — never presented to the whole team as "the new hire\'s verdict". Used to: (1) flag any trust/conflict issues, (2) set a baseline for re-administration at Day 90.',
      hrdoes_id: 'Membahas hasil secara privat dengan atasan tim — bukan dipresentasikan ke seluruh tim sebagai "penilaian anggota baru". Digunakan untuk: (1) sinyal awal masalah trust/conflict, (2) baseline untuk re-administrasi Day 90.',
      caveat_en: 'Day-30 reliability caveat: as a new hire at ~30 days you have limited team observation — you may not yet have seen a full conflict cycle or accountability crisis. Scores reflect early integration impressions, not a complete team health diagnostic. Recommended re-administration at Day 90.',
      caveat_id: 'Catatan reliabilitas Day-30: sebagai karyawan baru di ~30 hari, observasi tim Anda terbatas — mungkin belum melihat siklus konflik penuh atau krisis akuntabilitas. Skor mencerminkan kesan awal integrasi, bukan diagnostik tim lengkap. Direkomendasikan re-administrasi di Day 90.',
      caveatStrong: true,
    },
    {
      id: 'a7',
      seq: '07',
      milestone: 'd60',
      milestoneDay: 'Day 60',
      color: 'amber',
      ref: 'Hogan Development Survey® / Hogan Assessment Systems',
      title_en: 'Leadership Derailer Inventory',
      title_id: 'Inventori Derailer Kepemimpinan',
      tagline_en: 'Identifies unmanaged leadership strengths for coaching context',
      tagline_id: 'Identifikasi kekuatan kepemimpinan yang belum dikelola untuk konteks coaching',
      items: 66,
      itemsLabel_en: 'Likert items',
      itemsLabel_id: 'item Likert',
      minutes: 14,
      outputs: 11,
      outputsLabel_en: 'risk dimensions',
      outputsLabel_id: 'dimensi risiko',
      status: 'leadership-only',
      lockedReason_en: 'Leadership / high-potential track only — opens Day 55 if applicable',
      lockedReason_id: 'Hanya untuk jalur kepemimpinan / high-potential — terbuka Day 55 jika berlaku',
      what_en: 'Eleven tendencies that can become career derailers when extreme or unmanaged: Excitable, Skeptical, Cautious, Reserved, Leisurely, Bold, Mischievous, Colorful, Imaginative, Diligent, Dutiful. Each scored as Low / Moderate / High risk.',
      what_id: 'Sebelas tendensi yang bisa jadi derailer karier ketika ekstrem atau tidak dikelola: Excitable, Skeptical, Cautious, Reserved, Leisurely, Bold, Mischievous, Colorful, Imaginative, Diligent, Dutiful. Setiap dimensi diberi skor risiko (Rendah/Moderat/Tinggi).',
      why_en: 'Day 60 — you\'ve been here long enough to reflect on real experiences of stress and pressure. Derailers usually appear because of a strength — e.g. "Bold" = confident and courageous, but at extreme becomes overconfident. Coaching helps manage the shadow side.',
      why_id: 'Day 60 — Anda sudah cukup lama untuk merefleksikan pengalaman nyata stres dan tekanan kerja. Derailer biasanya muncul justru karena kekuatan tertentu — mis. "Bold" = percaya diri dan berani, tapi ekstrem menjadi overconfident. Coaching membantu mengelola sisi gelap dari kekuatan ini.',
      youget_en: 'Profile of all 11 derailers with risk levels, three-cluster analysis (Moving Away From People / Against People / Toward People), Top 3 priority derailers, and coaching questions for each.',
      youget_id: 'Profil 11 derailer dengan tingkat risiko, analisis 3 klaster (Moving Away From People, Against People, Toward People), Top 3 derailer prioritas, dan pertanyaan coaching untuk masing-masing.',
      hrdoes_en: 'Results are shared only with you and your coach/manager (if trained). Not for team documentation. Used as reflective material in 1-on-1 coaching, not as evaluation.',
      hrdoes_id: 'Hasil hanya dibagikan kepada Anda dan coach/atasan yang terlatih. Bukan untuk dokumentasi tim. Digunakan sebagai bahan refleksi dalam sesi coaching 1-on-1, bukan sebagai penilaian.',
      caveat_en: 'Adapted from the Hogan Development Survey® (HDS) construct — not an official administration. For onboarding coaching purposes only — not for selection decisions. Limited to the leadership / high-potential track, not all new hires.',
      caveat_id: 'Mengadaptasi konstruksi Hogan Development Survey® (HDS) — bukan administrasi resmi. Hanya untuk coaching onboarding — bukan keputusan seleksi. Terbatas pada jalur kepemimpinan / high-potential, bukan semua karyawan baru.',
      caveatStrong: true,
    },
  ];

  return {
    T, PHASES, MODULES, ACTIVE_MODULE_CONTENT, QUIZ, TRANSCRIPT,
    ASSIST_T, ASSIST_CATEGORIES, ASSIST_TRENDING,
    ASSIST_CONVERSATION, ASSIST_HISTORY, ASSIST_STARTERS,
    ASSESS_T, ASSESSMENTS,
  };

})();